version: '3.8'

services:
  postgres:
    container_name: survivor-nexus-database
    image: postgres
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survivor-nexus-database
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
